First page of my Web Developer Portfolio
D4nielJ/developer-portfolio pull request #1
Opened 2021-06-02 21:15 UTC by D4nielJ

## Hello Reviewer,

This is the first version of my Portfolio. First-page `nav` and `header` for mobile size were the main focus here.

Let me know of any changes or suggestions,

Cheers,
Daniel Jaramillo.

2021-06-02 22:15 UTC, Dipeshtwis requested changes
Hi @D4nielJ, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
👍 Page structure is looking good.
👍 Professional repo, with good commit message and PR title, keep up the good work 💪.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review._**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Check the comments under the review._**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 22:15 UTC, Dipeshtwis commented on index.html
> +    <nav>
- [x] Instead of nav, it should be header. `nav` always comes under the `header` tag as this helps with your page's readability and optimization.

2021-06-02 22:15 UTC, Dipeshtwis commented on index.html
> +        </div>
- [x] The logo should have a link (a tag). It makes it easier to move from another to home page.

2021-06-02 22:15 UTC, Dipeshtwis commented on index.html
> +        <div id="menu">
- [ ] Instead of `div`, it should be `nav`. To wrap menus we will use a `nav` tag as it will make code more readable.

2021-06-02 22:15 UTC, Dipeshtwis commented on index.html
> +      <p id="header-paragraph">
- Avoid using id so much. Instead, you can use class so that we will follow DRY (Do not repeat yourself) principle in CSS well.

2021-06-02 22:15 UTC, Dipeshtwis commented on index.html
> +    <header>
- [ ] This header should be replaced by a `section` tag. As it denotes section and also helps with the page's readability and optimization.

2021-06-02 22:15 UTC, Dipeshtwis commented on index.html
> +          <i class="fab fa-instagram"></i>
- [ ] The list of icons should use a `ul` tag to group them, and `li` per icon; each icon has a link (a tag).

2021-06-02 22:15 UTC, Dipeshtwis commented on README.md
> +
[Optional]
- It looks good. Also, I will suggest adding screenshots to show people your work in one scroll. 👍

2021-06-03 15:17 UTC, D4nielJ commented
This is the first version of my Portfolio. The first-page header, nav, and about-me section for mobile size were the main focus here.

Let me know of any changes or suggestions,

Also, here's a screenshot of how it's looking so far.

![Screenshot](https://i.imgur.com/wUrbo2v.png "Screenshot")

Cheers,
Daniel Jaramillo.

2021-06-03 15:32 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @D4nielJ     ! :wave: :wave:

#### You have done really well in implementing the previously required changes.

 However, there are changes required for you to make in order for this project to be approved. 
- - -

### **Recommended** ♻️

_There are a few changes you skipped, see the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 1 more reviews as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-03 15:32 UTC, Temmarie commented on index.html
> +        <div id="social-media-container">
- [ ] Avoid using `id` so much. Instead, you can use `class` so that we will follow DRY (Do not repeat yourself) principle in CSS well.

2021-06-03 16:34 UTC, Temmarie approved these changes
# Status: Approved ✔️ 
## Hi @D4nielJ  , 
#### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
#### Congratulations! 🎉 

### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- Check out [this](https://www.w3schools.com/html/html_id.asp) link that explains `id`s and `classes` as well as their differences and importance.

#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

2021-06-03 16:45 UTC, merged